### ISSUE TITLE
Backpack doesn't appear on player model when equipped in Curios slot

### ISSUE THREAD

**Issue by anIceyGirl** [yzl210/CuriosQuarkOBP#1]
Exactly what the title suggests. I've got the backpack itself equipped, and while it does grant me the extra inventory slots, it doesn't show up on my player's model.

This isn't, like, completely game breaking, but it's just a little bit odd to me.
![image](https://user-images.githubusercontent.com/35877888/107514532-cc6e6800-6b77-11eb-90e8-865ee2bc933b.png)

**Comment by yzl210** [comment]
This is in todo list: https://github.com/yzl210/CuriosQuarkOBP/blob/1.16/src/main/java/cn/leomc/curiosquarkobp/CurioBackpack.java#L25

**Comment by anIceyGirl** [comment]
Alright. Thank you very much for the quick response.
