### ISSUE TITLE
[1.19.2 Forge] DUPING Aritfacts and (any items) and CuriousSlots in Backpack #4314

### ISSUE THREAD

**Issue by GitJhopa** [yzl210/CuriosQuarkOBP#11]
see video: https://youtu.be/2rkIJ1YYvc4

Dupe artifacts and other items that can be placed in Curious, must be wearing a backpack. I also use the Curious BackPack mod.

To dupe, the inventory must be full.

**Comment by GitJhopa** [comment]
I can dupe do absolutely anything

**Comment by GitJhopa** [comment]
https://github.com/VazkiiMods/Quark/issues/4314

**Comment by yzl210** [comment]
Fixed
