### ISSUE TITLE
[Feature Request] Forbid putting a backpack in an armor slot

### ISSUE THREAD

**Issue by GitJhopa** [yzl210/CuriosQuarkOBP#12]
I found a bug that with your mod you can put on 2 backpacks, one in the Curios slot, the other in the armor slot. Can you make if your addon is installed, then the backpack cannot be placed in the armor slot? And then the players cheat using 2 backpacks.

**Comment by yzl210** [comment]
I've known about this problem for a long time, but haven't come up with a solution because the issue is that I cannot cancel the LivingEquipmentChangeEvent due to vanilla and its implementation.

**Comment by yzl210** [comment]
How about when the player tries to wear another backpack in the armor slot, the backpack is removed and put in their inventory/dropped on the ground?

**Comment by GitJhopa** [comment]
Does not work well, visually buggy.

**Comment by GitJhopa** [comment]
Forbid putting a backpack into the armor slot at all so that it is not put on there, otherwise you made it visually buggy, it is put on and instantly removed.
