### ISSUE TITLE
Game doesn't load due to an error with this mod

### ISSUE THREAD

**Issue by vizthex123** [yzl210/CuriosQuarkOBP#13]
Disabling the mod makes it load fine.

Log:
[latest.log](https://github.com/yzl210/CuriosQuarkOBP/files/12773483/latest.log)

Issue message in-game:
![image](https://github.com/yzl210/CuriosQuarkOBP/assets/31721920/5dac69e2-adfb-4cee-a3d1-3f09bd925bae)

**Comment by yzl210** [comment]
I can't reproduce with the latest quark.
<img width="263" alt="image" src="https://github.com/yzl210/CuriosQuarkOBP/assets/32786985/5bb18f91-d8a4-4aef-a2c1-f7883ce7eb93">

**Comment by vizthex123** [comment]
Weird, I just tested it again and it seems like enabling this causes [Deep Dark Regrowth](https://www.curseforge.com/minecraft/mc-mods/deep-dark-regrowth) to cause the crash. Disabling either mod fixes it, but hopefully it gets properly fixed soon.

Reported this to that mod's dev.

**Comment by yzl210** [comment]
Log?

**Comment by vizthex123** [comment]
Ah, sorry. Here ya go: https://gist.github.com/vizthex123/8c813b2dfe64cc4d22fecfa8bfcf63fb

**Comment by yzl210** [comment]
This is a different crash. I don't see any relationship with my mod just from the log, and since his mod is not open source, I can't determine what's happening

**Comment by vizthex123** [comment]
it's the same log i sent him, but yeah i guess we'll have to see if he fixes it.

mind leaving the issue open as a warning to anyone trying to use both mods?

**Comment by vizthex123** [comment]
ok, it seems like the Quark update fixed the crash. Had both enabled and loaded into my game fine. Gonna close the issue then, thanks for your help.
