### ISSUE TITLE
Crafting Table Invisible

### ISSUE THREAD

**Issue by BuilderDan** [yzl210/CuriosQuarkOBP#2]
When the backpack is equipped, for some reason the personal player inventory crafting turns items invisible in the output. There might be another mod messing with the visual, but I have to do more testing for that, however, I wanted to report it initially in case it was not known and there was an easy fix for it. It might be a Curios bug, but I cannot tell for sure yet. clarity would be helpful.

**Comment by Foozey** [comment]
The mod that messes with this is FastWorkbench.
