### ISSUE TITLE
1.18.1 - Backpack on wrong position

### ISSUE THREAD

**Issue by UncleSam139** [yzl210/CuriosQuarkOBP#5]
The screenshot tells everything. 

![2022-01-07_21 36 25](https://user-images.githubusercontent.com/41263727/148656899-773cfe8f-79f8-4f1a-907b-9b6efd4e8def.png)

**Comment by yzl210** [comment]
It's fine for me: 
![image](https://user-images.githubusercontent.com/32786985/148669180-2543d1a8-543b-46fc-b1a1-f520c426d8ef.png)
What other mods have you installed?

**Comment by UncleSam139** [comment]
That's all mods I'm using.

Cycle Paintings (Forge) (by Serilum)
Just Enough Items (JEI) (by mezz)
Toast Control (by Shadows_of_Fire)
ZeroCore 2 (by ZeroNoRyouki)
Enchantment Descriptions (by DarkhaxDev)
Rechiseled (by SuperMartijn642)
RFTools Base (by McJty)
Scaffolding Drops Nearby (Forge) (by Serilum)
Just Enough Keys [JEK] [Forge] (by starmun)
Storage Drawers (by Texelsaur)
Let Sleeping Dogs Lie (by ohaiiChun)
AppleSkin (by squeek502)
Vine Collector (by AlexProgrammer)
Sound Physics Remastered (by henkelmax)
Sound Categories (by stashymane)
Dungeon Crawl (by xiroc_)
GraveStone Mod (by henkelmax)
Cloth Config API (Forge) (by shedaniel)
Xaero's World Map (by xaero96)
FastSuite (by Shadows_of_Fire)
Curios Quark Oddities Backpack (by 6LeoMC)
RFTools Builder (by McJty)
Jade 🔍 (by Snownee_)
KleeSlabs (by BlayTheNinth)
Chisels & Bits - For Forge (by AlgorithmX2)
RFTools Control (by McJty)
Stupid Horse Stand Still (by Lothrazar)
SuperMartijn642's Core Lib (by SuperMartijn642)
RFTools Utility (by McJty)
SwingThroughGrass (by exidex)
Immersive Engineering (by BluSunrize)
FastFurnace (by Shadows_of_Fire)
Biomes O' Plenty (by Forstride)
Crafting Tweaks (by BlayTheNinth)
Create (by simibubi)
SuperMartijn642's Config Lib (by SuperMartijn642)
Softer Hay Bales (Forge) (by Serilum)
ChickensShed (by holmraven)
Extreme Reactors (by ZeroNoRyouki)
McJtyLib (by McJty)
Weaker Spiderwebs (Forge) (by Serilum)
RFTools Storage (by McJty)
Catalogue (by MrCrayfish)
Tumbleweed (by bconv)
Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)
NetherPortalFix (by BlayTheNinth)
Drawers Tooltip (by Snownee_)
Hidden Recipe Book (Forge) (by Serilum)
RFTools Power (by McJty)
Quark (by Vazkii)
Just Enough Resources (JER) (by way2muchnoise)
Effective (Forge) (by BottomTextDanny)
Balm (Forge Edition) (by BlayTheNinth)
CreativeCore (by CreativeMD)
Just Enough Professions (JEP) (by Mrbysco)
Collective (Forge) (by Serilum)
Snow Under Trees (by bl4ckscor3)
Clumps (by Jaredlll08)
Cherished Worlds (Forge) (by TheIllusiveC4)
Better Advancements (by way2muchnoise)
Quark Oddities (by Vazkii)
AutoRegLib (by Vazkii)
TerraBlender (by TheAdubbz)
RevampedWolf (by bagu_chan500)
Fast Leaf Decay (by olafskiii)
ItemZoom (by mezz)
Advanced Chimneys (by EnderLanky)
Curios API (Forge) (by TheIllusiveC4)
Configured (by MrCrayfish)
FastWorkbench (by Shadows_of_Fire)
ForgeEndertech (by EnderLanky)
Applied Energistics 2 (by AlgorithmX2)
XNet (by McJty)
Mouse Tweaks (by YaLTeR)
Flywheel (by jozufozu)
More Overlays Updated (by RiDGo8)
Torch Slabs Mod (by EndlesNights)
Not Enough Crashes (Forge) (by NatanFudge)
Xaero's Minimap (by xaero96)
Placebo (by Shadows_of_Fire)
AmbientSounds 5 (by CreativeMD)

**Comment by MrJorman** [comment]
too problem

**Comment by yzl210** [comment]
I can’t reproduce the issue, did you install optifine?

**Comment by MrJorman** [comment]
Rubidium.

**Comment by MrJorman** [comment]
You need to take a backpack and just click on it with the right click so that it goes to Curious slots at the very beginning.

**Comment by MrJorman** [comment]
If you first put it in the armor slot, then it will be displayed correctly in Curios

**Comment by MrJorman** [comment]
@yzl210

**Comment by MrJorman** [comment]
I checked without other mods - the bug really exists. As soon as you create a world or connect to the server, put your backpack right into the Curious slots.

**Comment by yzl210** [comment]
Thanks for providing the steps to reproduce this issue.
