### ISSUE TITLE
start game

### ISSUE THREAD

**Issue by MrJorman** [yzl210/CuriosQuarkOBP#7]
[crash-2022-06-15_14.35.32-fml.txt](https://github.com/yzl210/CuriosQuarkOBP/files/8908888/crash-2022-06-15_14.35.32-fml.txt)

**Comment by yzl210** [comment]
What's the mod quarkfix?

**Comment by MrJorman** [comment]
these are my fixes for Quark mod

**Comment by MrJorman** [comment]
on the server, your mod has started, but does not want to on the client

**Comment by yzl210** [comment]
Hmm, if you are a modder, you should be aware that your mixin is having problems.

**Comment by yzl210** [comment]
I think its because I changed the parameter of [this method](https://github.com/yzl210/CuriosQuarkOBP/commit/b26e7563df4220045629d6f39b2aa4cff79cef0a#diff-4a66a0eb9a78cb465bce9f35a5ce6a28d3e3bd98c649122423cde27e97f40248R43). You need to change in your mixin accordingly.

**Comment by MrJorman** [comment]
thank!
